# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']

# Site Settings
title: "Google Developer Group Catania"
email: "main@gdgcatania.org"
description: "GDG Catania community"
baseurl: ""
url: "https://gdgcatania.org"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-x.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Google Developer Group Catania"
organizerAlternateName: "Google Developer Group Catania"
organizerDescription: "Community aperta e volontaria che crea progetti e condivide le esperienze sulla tecnologia di Google con passione"
organizerEmail: "main@gdgcatania.org"
organizerLogo: "/img/seo/gdg-catania-logo.png"
organizerLink: "http://gdgcatania.org/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, Catania"
twitterAccount: "@gdgcatania"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "<typeout>"
eventDate: "Catania"
typeoutTextValues: '"", "Google Developer Group"'
typeoutFallback: "Google Developer Group"
heroButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
 - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "Cosa si fa in un GDG?"
aboutBlock:
 - {title: "Learn", image: "iconBrain.png", text: "Corsi, workshop, bootcamp, conferenze, codelab, hackathon, tutorship, dibattiti, dispositivi e risorse di studio ad uso gratuito, accesso agevolato ad eventi esterni di formazione e ad esami di certificazione, in breve: tutto ciò di cui hai bisogno per apprendere e specializzarti attorno all’universo delle tecnologie di sviluppo e le metodologie di design made in Google." }
 - {title: "Build", image: "iconCode.png", text: "Sei un esperto sviluppatore/designer, un aspirante o semplicemente un appassionato? Sai scrivere articoli, realizzare video o gestire progetti editoriali? Il GDG è una buona occasione per metterti alla prova e cimentarti nella realizzazione di progetti di sviluppo, design e publishing, lavorando e coordinandoti con altri membri della community." }
 - {title: "Share", image: "iconIdea.png", text: "Il GDG è una community di appassionati unicamente costituita da e fondata su volontari. Ciascuna opportunità che il GDG ti offre è possibile grazie al loro lavoro di condivisione di propri progetti e competenze, senza alcuna retribuzione. Hai dunque realizzato o stai realizzando un progetto? Hai delle competenze tecniche? Condividere tutto ciò è sicuramente un ottimo modo per sostenere il GDG e “restituire” qualcosa alla community." }
 - {title: "Connect", image: "iconJoin.png", text: "Prendere parte alle nostra attività ti consentirà di incontrare, parlare e condividere le tue idee e i tuoi lavori con numerosi professionisti e appassionati del settore, sia locali che di fama internazionale." }
 - {title: "Organize", image: "iconSocial.png", text: "Condividere non è l’unico modo di dare una mano al GDG. L’altro modo per contribuire è prendere parte alle attività organizzative di un evento e di altre attività cardine della community. Ti occupi di comunicazione? Sai gestire campagne promozionali? Sei in grado di organizzare eventi? Sai gestire le relazioni con il pubblico e le questioni di segreteria? O anche semplicemente… spostare le sedie? Beh, allora puoi sicuramente dare il tuo contributo anche in questi termini." }
 - {title: "Have Fun", image: "iconHello.png", text: "Il GDG è un ambiente sano di persone che amano l’umanità verso gli altri e la dinamicità. Nel GDG troverai ragazze e ragazzi sempre pronti ad aiutarti, cortesi, cordiali, umili e ricchi di ironia ed allegria, ma anche intraprendenti, propositivi e dalle idee dirompenti. Nel GDG non c’è spazio per gli antagonismi e la cattiveria, poiché la lealtà e il rispetto reciproco stanno alla base dei valori della community. Nel GDG è sostanzialmente semplice trovare dei buoni amici con i quali trascorrere dei momenti tanto formativi quanto divertenti." }

# Follow us Block
followusTitle: "Follow us"
followusBlockImage: "social-bg.jpg"
followusItems:
  - {name: "Facebook", image: "facebook.png", link: "https://facebook.com/gdgcatania"}
  - {name: "Telegram", image: "telegram.png", link: "https://telegram.me/joinchat/BaFZOD-uNCm1Xd3usSxeuA"}
  - {name: "Forum", image: "NodeBB.png", link: "http://forum.gdgcatania.org"}

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "1226", specialCharacter: "+", info: "Partecipanti", detail: "da tutta Italia"}
 - {count: "350", specialCharacter: "+", info: "Membri", detail: " attivi negli ultimi 6 mesi "}
 - {count: "25", specialCharacter: "+", info: "Eventi", detail: "organizzati negli ultimi 6 mesi"}

# Latest News Block
latestNewsTitle: "Cos'è un Google Developer Group?"

# StaffGDG
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 6
rockstarSpeakersTitle: "Main GDG Catania"
rockstarSpeakersButtonText: ""

# Foto Block
venueBlockTitle: "Community"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueSmallImage4: "venue_4.jpg"

# Partners Block
partnersTitle: "Partners"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Iscriviti per restare aggiornato!"
subscribeAction: "https://gdgcatania.us-50.list-manage.com/subscribe/post?u=fb72f52c09a716847b7389a39&id=f723af0519"
subscribeInfo: "Join us!"

# Next Event Block
nextEventTitle: "What's next"
nextEventImage: "next-event.jpg"
nextEventItems:
- {name: "Evento Facebook", image: "facebook.png", link: "https://www.facebook.com/events/511846149196052"}
- {name: "Eventbrite", image: "eventbritew.png", link: "https://www.eventbrite.it/e/biglietti-gdg-devfest-mediterranean-2017-cap-2-38979541859"}


# Footer
socialLinks:
 - {link: "https://facebook.com/gdgcatania/", icon: "facebook"}
 - {link: "https://plus.google.com/118102220008611585984", icon: "google-plus"}
 - {link: "https://www.youtube.com/channel/UCetkWXxUNcJ8T4eLC9FJ5Cw", icon: "youtube"}
 - {link: "https://twitter.com/gdgcatania", icon: "twitter"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://developers.google.com/groups/chapter/118102220008611585984/", text: "GDG Catania"}
   - {link: "https://developers.google.com", text: "Google Developers"}
   - {link: "https://www.womentechmakers.com/", text: "Women Techmakers"}
   - {link: "https://sites.google.com/wtmitalia.it/wtm/home", text: "Women Techmakers Italia"}
 -
  title: "Contatti"
  links:
   - {link: "mailto:main@gdgcatania.org", text: "main@gdgcatania.org"}

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."
